spring.application.name=Plataforma Citas

server.port=${PORT:8080}

spring.datasource.url=jdbc:sqlite:plataforma_citas.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false